# Generated by Django 6.0.7 on 2026-08-03 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Topnoz', max_length=100)),
                ('contact_email', models.EmailField(default='support@topnoz.com', max_length=254)),
                ('contact_phone', models.CharField(default='+880 1234 567 890', max_length=20)),
                ('facebook_link', models.URLField(blank=True, null=True)),
                ('instagram_link', models.URLField(blank=True, null=True)),
                ('free_delivery_threshold', models.IntegerField(default=5000, help_text='Amount in Taka for free delivery')),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
