# Generated by Django 6.0.7 on 2026-08-03 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Processing', 'Processing'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
