# Generated by Django 6.0.7 on 2026-08-04 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_customerorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='available_sizes',
            field=models.CharField(blank=True, help_text='Enter sizes separated by comma (e.g., S, M, L, XL)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='order',
            field=models.IntegerField(default=0, help_text='Optional. Higher number = shows first. Default 0 uses newest first.'),
        ),
    ]
