# Generated by Django 6.0.7 on 2026-08-05 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='chatsession',
            table='chat_chatsession',
        ),
        migrations.AlterModelTable(
            name='fashiontip',
            table='chat_fashiontip',
        ),
    ]
