# Generated by Django 5.2 on 2025-06-05 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0002_orderitem_customer_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='categories',
            field=models.CharField(choices=[('ME', "Men's Wear"), ('WO', "Women's Wear"), ('KI', 'Kids Wear'), ('AC', 'Accessories'), ('OT', 'Other')], max_length=10),
        ),
    ]
