# Generated by Django 5.2 on 2025-06-30 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0003_alter_item_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='products',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='quantities',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
