# Generated by Django 5.2 on 2025-06-30 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0004_customerorder_products_customerorder_quantities'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='product_type',
            field=models.CharField(choices=[('shirt', 'Shirt'), ('polo-tshirt', 'Polo Tshirt'), ('tshirt', 'Tshirt'), ('punjabi', 'Punjabi'), ('pant', 'Pant'), ('footware', 'Footware'), ('lifestyle', 'Lifestyle')], default='shirt', max_length=20),
        ),
    ]
