# Generated by Django 5.2 on 2025-06-30 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0005_item_product_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='categories',
        ),
    ]
