# Generated by Django 5.2 on 2025-07-01 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0007_itemmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmedia',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='products/videos/'),
        ),
    ]
