# Generated by Django 4.2.23 on 2025-07-06 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0009_item_order'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customerorder',
            table='web_customerorder',
        ),
        migrations.AlterModelTable(
            name='item',
            table='web_item',
        ),
        migrations.AlterModelTable(
            name='itemmedia',
            table='web_itemmedia',
        ),
        migrations.AlterModelTable(
            name='itemvariation',
            table='web_itemvariation',
        ),
        migrations.AlterModelTable(
            name='order',
            table='web_order',
        ),
        migrations.AlterModelTable(
            name='orderitem',
            table='web_orderitem',
        ),
        migrations.AlterModelTable(
            name='variation',
            table='web_variation',
        ),
    ]
