# Generated by Django 4.2.23 on 2025-07-07 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0010_alter_customerorder_table_alter_item_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='sizes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
