# Generated by Django 6.0.7 on 2026-08-05 18:31

from django.db import migrations
from django.contrib.auth.hashers import make_password

def create_superuser(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    if not User.objects.filter(username='admintopnoz').exists():
        User.objects.create(
            username='admintopnoz',
            email='admin@topnoz.com',
            password=make_password('Tanvir@Rifat'),
            is_staff=True,
            is_superuser=True,
            is_active=True
        )

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_referrer_url_and_more'),
    ]

    operations = [
        migrations.RunPython(create_superuser),
    ]
